#!/bin/sh

query=$(printf '%s' "$*" | tr ' ' '+' )
# default web source
magnet=$(curl -s http://rutor.org/search/0/0/100/0/$query | grep -Po "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" | head -n 1)
# optional web source
#magnet=$(curl -k -s "https://nyaa.si/?f=0&c=0_0&q=${query}" | grep -Po "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" | head -n 1)
peerflix $magnet --list --vlc
